version: '3.6'

services:
  web:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - app-network
  api:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_DATABASE_NAME=example_db
      - DB_USERNAME=example_user
      - DB_PASSWORD=example_password
      - DB_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network
  db:
    container_name: mysql
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=example_db
      - MYSQL_USER=example_user
      - MYSQL_PASSWORD=example_password
    ports:
      - '3306:3306'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    environment:
      - PMAHOST=db
    ports:
      - "8081:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
